site_name: Monaco
repo_url: https://github.com/servinagrero/monaco
repo_name: monaco
edit_uri: ""

theme:
    hljs_style: github
    logo: img/logo.svg
    name: material
    palette:
        - scheme: default
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
          primary: white
          accent: light green
        - scheme: slate
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
          primary: white
          accent: green
    font:
        text: IBM Plex Sans
        code: JetBrains Mono
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.sections
        - navigation.expand
        - content.tabs.link
        - toc.integrate
        - content.code.annotate

extra_css:
  - stylesheets/extra.css
  
plugins:
  - search
  - autorefs
  - mkdocstrings
  
  
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  
nav:
    - Introduction: index.md
    - Getting started: starting.md
    - Usage: usage.md
